version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgress
    ports:
      - "5433:5432"
  rails:
    build: .
    image: danghieu193/money-divider-api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/myapp
      - ./tmp:/myapp/tmp/
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      RDS_DB_NAME: ${RDS_DB_NAME}
      RDS_USER: ${RDS_USER}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_ENDPOINT: ${RDS_ENDPOINT}
      RDS_PORT: ${RDS_PORT}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SECRET_TOKEN: ${SECRET_TOKEN}
    depends_on:
      - db
